# Morphological Image processing 
معالجة الصور المورفولوجية هي تقنية غير خطية تستخدم علم التشكل الرياضي لتحليل ومعالجة الصور الرقمية. يعتمد على فكرة أن شكل وبنية كائن في صورة ما يمكن تمثيله باستخدام العمليات الحسابية.

العناصر الأساسية لمعالجة الصور المورفولوجية هي عناصر هيكلية ، وهي عبارة عن أشكال صغيرة (عادة مربعات أو دوائر) تُستخدم لمسح صورة ضوئيًا ومقارنة وحدات البكسل بشكل عنصر الهيكلة. العمليات المورفولوجية الأكثر شيوعًا هي التعرية والتمدد والفتح والإغلاق.

Erosion_ هي عملية تؤدي إلى تآكل حدود الكائن في الصورة ، مما يقلل من حجمها.

  Dilation_ هي عملية تقوم بتوسيع حدود كائن في صورة ما ، مما يؤدي إلى زيادة حجمه.

OPENING_ هي عملية تؤدي إلى تآكل الصورة ثم توسيعها ، مما يؤدي إلى إزالة وحدات البكسل الصغيرة المعزولة (التشويش) والفجوات الموجودة في الكائن.

  __CLOSING__ هي عملية تقوم بتوسيع الصورة ثم تآكلها ، مما يؤدي إلى ملء الفجوات والثقوب الصغيرة في الكائن.

يمكن تطبيق هذه العمليات على الصور الثنائية والصور ذات التدرج الرمادي والصور الملونة. يمكن استخدامها في مجموعة متنوعة من المهام ، مثل تجزئة الصورة وتقليل الضوضاء واكتشاف الكائنات واستعادة الصورة. بالإضافة إلى ذلك ، يمكن دمج معالجة الصور المورفولوجية مع تقنيات معالجة الصور الأخرى مثل التصفية ، والحد من الحواف واكتشاف الحواف لتحسين النتائج.

تُستخدم معالجة الصور المورفولوجية على نطاق واسع في العديد من المجالات مثل التصوير الطبي والفحص الصناعي وتحليل صور الأقمار الصناعية ، من بين أمور أخرى. يسمح باستخراج ميزات الصورة ، والتي يصعب استخلاصها بطرق أخرى ، وتحليل شكل وهيكل الكائنات في الصورة

In [ ]:
import cv2
import numpy as np

In [ ]:
img=cv2.imread("Trakpar.png",0)
_,mask=cv2.threshold(img,220,250,cv2.THRESH_BINARY_INV)

Kernal=np.ones((5,5),np.uint8)
Kernal_=np.ones((3,3),np.uint8)
dilation=cv2.dilate(mask,Kernal_,iterations=2)
erosion=cv2.erode(dilation,Kernal,iterations=2)
opening=cv2.morphologyEx(mask,cv2.MORPH_OPEN,Kernal,iterations=1)
closing=cv2.morphologyEx(mask,cv2.MORPH_CLOSE,Kernal,iterations=1)


cv2.imshow('Gray',img)
cv2.imshow('Gray',mask)
# cv2.imshow('dilation',dilation)
# cv2.imshow('erosion',erosion)
# cv2.imshow('opening',opening)
# cv2.imshow('closing',closing)

cv2.waitKey(0)

cv2.destroyAllWindows()

# Somoothing or Blurring Images

### are used to remove the noise from the images and it use diverse linear
### because linear filter easy to achive and relatively fast 

### For example :-
* Blur
* Gaussian filter
* Median Filter
* Bilateral Filter


In [ ]:
import cv2
import numpy as np
img = cv2.imread("Older.png")
  
averaging=cv2.blur(img,(5,5))
Gaussian_F=cv2.GaussianBlur(img,(5,5),0)
median=cv2.medianBlur(img,5)
Bilateral=cv2.bilateralFilter(img,9,75,75)

cv2.imshow('Gray',img)
# cv2.imshow('averaging',averaging)
# cv2.imshow('Gaussian_F',Gaussian_F)
# cv2.imshow('median',median)
# cv2.imshow('Bilateral',Bilateral)

cv2.waitKey(0)
cv2.destroyAllWindows()


# Edge Detection using Laplacian

In [ ]:
import cv2
import numpy as np

img=cv2.imread("mesi.png")

lap=cv2.Laplacian(img,cv2.CV_64F,ksize=3)
lap=np.uint8(np.absolute(lap))


cv2.imshow('img',img)
cv2.imshow('Lapacian',lap)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Sobel X and Sobel Y edge detecion

In [3]:
import cv2
import numpy as np

img=cv2.imread("mesi.png")

sobel_X=cv2.Sobel(img,cv2.CV_64F,1,0)
sobel_Y=cv2.Sobel(img,cv2.CV_64F,0,1)
sobel_X=np.uint8(np.absolute(sobel_X))
sobel_Y=np.uint8(np.absolute(sobel_Y))

comine_sobel_X_and_Y=cv2.bitwise_or(sobel_X,sobel_Y)

cv2.imshow('Gray',img)
cv2.imshow('sobel_X',sobel_X)
cv2.imshow('sobel_Y',sobel_Y)
cv2.imshow('comine_sobel_X_and_Y',comine_sobel_X_and_Y)
# cv2.imshow('Bilateral',Bilateral)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Canny Edge Detection
### 1- convert image to gray scale 
### 2- remove the noise from the image by using gaussian filter which discuss befor 
### 3- use sobel X and Sobel Y to get the edges in two directions and combine them by using (Edge_Gradient)
### 4- apply Non-Maximum Suppression to make the edges thin
### 5- Hysteresis Thresholding to connect the strong edges and ignor other

In [6]:
import cv2
import numpy as np

img=cv2.imread("mesi.png")

canny=cv2.Canny(img,100,100)
cv2.imshow('canny',canny)

cv2.waitKey(0)
cv2.destroyAllWindows()

 # image pyramid (Gaussin pyramid and Laplacian pyrmid)

In [13]:
import cv2
import numpy as np

img=cv2.imread("mesi.png")
lr1=cv2.pyrDown(img)
lr2=cv2.pyrDown(lr1)
hr2=cv2.pyrDown(lr2)
pr=cv2.pyrUp(lr2)
cv2.imshow("Original image ",img)
cv2.imshow("lr1 ",lr1)
cv2.imshow("lr2 ",lr2)
cv2.imshow("hr2",pr)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
import cv2
import numpy as np

img=cv2.imread("mesi.png")
layer=img.copy()
gp=[layer]

for i in range(4):
    layer =cv2.pyrDown(layer)
    gp.append(layer)
    cv2.imshow(str(i),layer)
    
cv2.imshow("Original image ",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# find and draw contours 

In [ ]:
import numpy as np
import cv2

In [18]:
img=cv2.imread('log.png')
img=cv2.resize(img,(512,512))
imgray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ret,thresh=cv2.threshold(imgray,20,255,0)
contours,hierarchy=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE )
 
print("Number of contours = "+str(len(contours)))
print(contours[0])
cv2.drawContours(img,contours,-1,(0,255,0),3)
cv2.imshow("Image",img)
cv2.imshow('Image gray',imgray)
cv2.imshow("thresh",thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of contours = 14
[[[272 409]]

 [[271 410]]

 [[270 411]]

 [[269 411]]

 [[268 412]]

 [[267 412]]

 [[266 411]]

 [[265 411]]

 [[264 411]]

 [[263 411]]

 [[262 411]]

 [[261 411]]

 [[260 411]]

 [[259 411]]

 [[259 412]]

 [[259 413]]

 [[259 414]]

 [[259 415]]

 [[259 416]]

 [[259 417]]

 [[259 418]]

 [[259 419]]

 [[259 420]]

 [[259 421]]

 [[259 422]]

 [[259 423]]

 [[259 424]]

 [[259 425]]

 [[259 426]]

 [[259 427]]

 [[259 428]]

 [[259 429]]

 [[259 430]]

 [[259 431]]

 [[259 432]]

 [[259 433]]

 [[259 434]]

 [[259 435]]

 [[259 436]]

 [[259 437]]

 [[259 438]]

 [[259 439]]

 [[259 440]]

 [[259 441]]

 [[259 442]]

 [[259 443]]

 [[259 444]]

 [[259 445]]

 [[259 446]]

 [[259 447]]

 [[259 448]]

 [[259 449]]

 [[259 450]]

 [[259 451]]

 [[259 452]]

 [[259 453]]

 [[259 454]]

 [[259 455]]

 [[259 456]]

 [[259 457]]

 [[259 458]]

 [[259 459]]

 [[259 460]]

 [[259 461]]

 [[260 462]]

 [[261 463]]

 [[262 463]]

 [[263 463]]

 [[264 463]]

 [[265 462

# Motion Detection  and Tracking

In [1]:
import cv2
import numpy as np

cap=cv2.VideoCapture(1)

fram_width=int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height=int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fourcc=cv2.VideoWriter_fourcc(*'XVID')
out=cv2.VideoWriter("Detect.avi",fourcc,30,(1280,720))
            
ret,frame_1=cap.read()
ret,frame_2=cap.read()
while cap.isOpened():
        diff=cv2.absdiff(frame_1,frame_2)
        gray=cv2.cvtColor(diff,cv2.COLOR_BGR2GRAY)
        blur=cv2.GaussianBlur(gray,(5,5),0)
        
        _,threshould=cv2.threshold(blur,60,255,cv2.THRESH_BINARY)
        dilated=cv2.dilate(threshould,None,iterations=10)
        contours,_=cv2.findContours(dilated,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
        draw=cv2.drawContours(frame_1,contours,-1,(0,255,0),2)

        for contour in contours:
            (x,y,w,h)=cv2.boundingRect(contour)
            
            if cv2.contourArea(contour)<900:
                 continue
            cv2.rectangle(frame_1,(x,y),(x+w,y+h),(0,255,0),2)
            cv2.putText(frame_1,"Status : movement",(10,20),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),3)
                 
        image=cv2.resize(frame_1,(1280,720))
        out.write(image)
        cv2.imshow("Motion detection",frame_1)
                
        cv2.imshow("threshould ",threshould)
        cv2.imshow("dilated ",dilated)
                 
        frame_1=frame_2
        ret,frame_2=cap.read()
                 
        if cv2.waitKey(60)==27:
                 break

                 
     
cv2.destroyAllWindows()              
cap.release()               
out.release()               
                 
                 